- .idea/compiler.xml
- .idea/gradle.xml
- .idea/misc.xml
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-14__3_41__Default_Changelist_.xml
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-14__4_03__Default_Changelist_.xml
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-14_오후_3_41_[Default_Changelist]/shelved.patch
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-14_오후_4_03_[Default_Changelist]/shelved.patch
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-15__7_55__Default_Changelist_.xml
- .idea/shelf/Uncommitted_changes_before_Update_at_2020-11-15_오후_7_55_[Default_Changelist]/shelved.patch
- app/src/main/java/com/example/persimmon_tree_proj/CodeActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/familyactivity.java
- app/src/main/res/layout/activity_code.xml
- app/src/main/res/layout/activity_familyactivity.xml
> family check first

- app/build.gradle
- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
- app/src/main/res/layout/activity_log_inactivity.xml
> [add] google_login

- app/src/main/res/layout/activity_log_inactivity.xml
- app/src/main/res/layout/activity_registeractivity.xml
> '[fix] login_page UI'

- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/UserModel.java
> [add] firebase db

- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/UserModel.java
회원가입 시 작성하는 다른 회원 정보 
회원가입과 동시에 firebase database에 업로드
(주석 아직 안 썼오 추가 예정!)
> [fix] fix signup & upload to database

- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
회원가입 페이지에서 firebase database에 올리는 부분
주석 추가했슴니다
> [add] add comment in Registeractivity.java

- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
> [fix] firebase upload name

- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
> [fix] auto login

- .idea/misc.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Answeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
- app/src/main/res/layout/activity_answeractivity.xml
- app/src/main/res/layout/activity_main.xml
answeractivity/ Mainactivity xml 추가
> answeractivity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Calendar.java
- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
- app/src/main/res/layout/activity_calendar.xml
- app/src/main/res/layout/activity_registeractivity.xml
> [fix] agreement 

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MypageActivity.java
- app/src/main/res/layout/activity_answeractivity.xml
- app/src/main/res/layout/activity_calendar.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_mypage.xml
메인에서 마이페이지 넘어가는 거랑 돌아오는 버튼,
마이페이지 구성하는 요소들 일부 추가
> [add] mypage_activity

- app/src/main/java/com/example/persimmon_tree_proj/CodeActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/familyactivity.java
- app/src/main/res/layout/activity_code.xml
- app/src/main/res/layout/activity_familyactivity.xml
1. sharing fcode
2. check fcode
> complete soobin

- .idea/gradle.xml
- .idea/misc.xml
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/profile_color.java
- app/src/main/java/com/example/persimmon_tree_proj/profile_gam.java
- app/src/main/res/drawable/btn_clicked.xml
- app/src/main/res/drawable/btn_clicked_color.xml
- app/src/main/res/layout/activity_profile_color.xml
> [fix] profile gam and color

- app/src/main/java/com/example/persimmon_tree_proj/CodeActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
가족 코드를 생성한 경우 , 가족 프로필을 모두 작성한 이후 fcode가 올라갈 수 있도록 함.
만약, 가족 프로필을 작성하지 않은채 다시 앱에 접속하게 되면, 다시 fcode를 받음.
> [fix]make_familyacitivity

- app/src/main/java/com/example/persimmon_tree_proj/CodeActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MakeProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/MypageActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/familyactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/profile_color.java
- app/src/main/java/com/example/persimmon_tree_proj/profile_gam.java
> [fix] revising intent

- app/src/main/java/com/example/persimmon_tree_proj/Answeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MypageActivity.java
> [fix] intent

- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_share_calendar.xml
> [fix] calendar.xml

- app/src/main/java/com/example/persimmon_tree_proj/ShareCalendarActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
- app/src/main/java/com/example/persimmon_tree_proj/plan_bar.java
- app/src/main/res/layout/day.xml
- app/src/main/res/layout/plan_bar.xml
여러 날짜 보이게 수정
아직 한 날짜에 여러명 있는 부분은 못함
> [fix] can show many event

- app/src/main/java/com/example/persimmon_tree_proj/ShareCalendarActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
> [fix] show all events in all month

- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
- app/src/main/res/layout/day.xml
날짜 위로 안 떠오르게 일정하게 정렬,
한 날에 여러 일정 잘 뜨게 바꿈
> [fix] calendar view 

- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
- app/src/main/res/drawable/line_dungle.xml
> [fix] calendar drawable

- app/src/main/java/com/example/persimmon_tree_proj/PopupCalendar.java
- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
- app/src/main/res/drawable/line_dungle_calendar.xml
- app/src/main/res/layout/dayforpopup.xml
팝업용 day_xml 따로 만들어서 팝업 캘린더에 적용,
일정 바 용 둥근 테두리 하나 더 만들어서 적용시킴
> [fix] make one more day_xml and revise radius

- app/src/main/res/layout/day.xml
> [fix] calendar ratio

- app/src/main/java/com/example/persimmon_tree_proj/PopupcalActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/ShareCalendarActivity.java
- app/src/main/res/layout/activity_share_calendar.xml
- app/src/main/res/layout/day.xml
- app/src/main/res/layout/popup_plan.xml
한 날에 한 사람이 여러 일정 올리면 캘린더랑 팝업에도 잘 뜨게
> [fix] one day many plan 

- app/src/main/java/com/example/persimmon_tree_proj/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/MypageActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/PopupcalActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/ShareCalendarActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/adapter/CalendarAdapter.java
- app/src/main/java/com/example/persimmon_tree_proj/adapter/Plan_listview_Adapter.java
일정 팝업에서 왼쪽으로 스와이프 하면 수정 삭제 버튼 생기는 기능 추가
+) 눌렀을 때 이후의 기능은 아직
+) 일정 삭제, 추가시 대기자 화면이 plan_bar가 마구잡이로 생기는 것을 고침
-> addsinglevalue 어쩌고로 바꿈 !! ->얘는 한번만 실행
> [fix] swipe delete_btn

- app/src/main/java/com/example/persimmon_tree_proj/Popup_Cal/popup_RevisePlan.java
> [fix] error

- app/src/main/java/com/example/persimmon_tree_proj/log_inactivity.java
아예 새 폰에서 가입하면 안되는 거 오류 수정
--> 두번 로그인하면 자동로그인 됨
첫 번째는 자동로그인 저장 없이 로그인
두 번째는 자동로그인 저장하면서 로그인
세 번째부터는 자동 로그인
> [fix] login error

- app/src/main/java/com/example/persimmon_tree_proj/Registeractivity.java
- app/src/main/res/layout/activity_answeractivity.xml
- app/src/main/res/layout/activity_registeractivity.xml
> [fix] register activity

- app/src/main/java/com/example/persimmon_tree_proj/Account/KaKaoAuth.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/Registeractivity_1.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
> [add] kakaoauth

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Account/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/familyactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/MakeProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/MakeProfilemain.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/MypageActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/profile_color.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/profile_color_main.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/profile_gam.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/profile_gam_main.java
- app/src/main/res/layout/activity_loding_page_.xml
> [add] lodingpage

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Account/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/Registeractivity_1.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/more_information_activity.java
- app/src/main/res/layout/activity_more_information_activity.xml
소셜 로그인 시 이름과 생일 따로 받을 수 있는 페이지 추가
> [add] more information

- app/google-services.json
- app/src/main/java/com/example/persimmon_tree_proj/Main/Answeractivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
구글로그인 ->  메인 들어가는 과정
메인에서 질문 받고 답변하는 과정에서 생기는 오류 수정
> [fix] user_name

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/list_adapter.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_todolist.xml
- app/src/main/res/layout/todolist_item.xml
투두리스트 페이지 추가
사진 사이즈에 맞게 동적으로 높이 조절하는 그리드 추가
기타 오류 수정
> [add] to do list 

- app/src/main/java/com/example/persimmon_tree_proj/Account/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Account/more_information_activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/MypageActivity.java
- app/src/main/res/layout/activity_log_inactivity.xml
- app/src/main/res/layout/activity_waitactivity.xml
loding activity 조건에 맞게 변경
개인 프로필 설정(이름, 생년월일) =) 감 색깔 설정 => 감 캐릭터 설정 => 별명 => 가족 코드 (가족 프로필까지 작성해야 코드가 올라간다.) => waitactivity
* 개인 프로필 : 이름 , 생년월일
* case 1-1: 개인 프로필을 설정하지 않았음.
*
* case 1-2: 개인 프로필을 설정하였음.
*      case 2-1 : 감 캐릭터를 설정하지 않았음. => profile_gam activity로 이동
*
*      case 2-2 : 감 캐릭터를 설정하였음.
*          case 3-1 : 감 색깔을 설정하지 않았음 => profile_color activity로 이동
*          case 3-2 : 감 색깔을 설정하였음
*                  case 4-1 : 별명을 설정하지 않았음 => makeprofile로 이동
*                  case 4-2 : 별명을 설정하였음.
*                      case 5-1 : 나와 연결된 가족 코드가 없음 => familyactivity로 이동
*                      case 5-2 : 나와 연결된 가족 코드가 있음
*                          case 6-1 : 가족을 기다리는 중임 => waitactivity로 이동
*                          case 6-2 : mainactivity에 이미 들어와있음 => mainacitivy로 이동
*
> [fix] loding activity

- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Profile/MypageActivity.java
로그인 시 비밀번호 일치 문제 해결
일단, 이메일 회원가입 완전히 구현 후에 주석 풀 예정
> [fix] login password

- app/src/main/java/com/example/persimmon_tree_proj/Account/LodingPage_Activity.java
Waitactivity에서 우리집 감나무를 시작하였으면, 그 인원 수대로 count를 올리도록 하였음.
사용자가 우리집 감나무를 시작한 경우 Loding page를 거칠 때 count를 이용하여
count가 데이터베이스에 등록되어 있으면, Main으로 바로 이동하고
count가 데이터베이스에 등록되어 있지 않으면 Waitactivity로 이동하는 코드를 구현하였음.
> [add] autologin go to main

- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/familyactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Mypage/MakeProfile.java
> [fix] background touch keyboard

- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/res/layout/activity_main.xml
> [fix] handler in main_activity

- app/src/main/java/com/example/persimmon_tree_proj/Account/log_inactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/familyactivity.java
database 수정
login 비밀번호 일치 오류 수정
> [fix] login / database

- app/src/main/java/com/example/persimmon_tree_proj/Family/CodeActivity.java
> [add] code

- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_make__familyprofilewait.xml
- app/src/main/res/layout/activity_waitactivity.xml
lodingpage 오류 개선
waitactivity 대기 인원 리스트뷰 추가
> [fix] lodingpage / waitactivity

- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/res/layout/activity_waitactivity.xml
시작하기 버튼 누르면 fcount 올라가도록 설정하였음.
> [add] waitactivity btn_start

- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
> [fix] loding

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Family/StartpopupActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/res/layout/activity_startpopup.xml
가족 시작하기시 경고창 
확인 누르면 파이어베이스에 count 올라가고
취소 누르면 waitactivity로 이동함.
> [add] startpopupActivity

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Family/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity2.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/familyactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/res/layout/activity_waitactivity2.xml
파이어베이스 captain 추가
captain true일 경우에 Waitacitivity로 이동
captain false일 경우에 Waitactivity2로 이동
> [add] Waitactivity2

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/Game_activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/TodoList_addlist_activity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todo_new.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/list_adapter.java
- app/src/main/res/drawable/todo_style1.xml
- app/src/main/res/drawable/todo_style2.xml
- app/src/main/res/drawable/todo_style3.xml
- app/src/main/res/drawable/todo_style4.xml
- app/src/main/res/layout/activity_todo_list_addlist_activity.xml
- app/src/main/res/layout/todolist_item.xml
뭐할감 기능 추가
- 새 메모 추가 기능
- 메모장 UI 수정 ( 동적으로 그리드 사이즈 조정 !! )
> [add] todolist 

- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Mypage/profile_color.java
> [fix] profile_color -> Makeprofile

- app/src/main/java/com/example/persimmon_tree_proj/Mypage/MypageActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Mypage/profile_color_main.java
- app/src/main/java/com/example/persimmon_tree_proj/Mypage/profile_gam_main.java
- app/src/main/res/layout/activity_mypage.xml
- app/src/main/res/layout/activity_profile_color_main.xml
- app/src/main/res/layout/activity_profile_gam_main.xml
> [add] profile_gam/color_main

- app/build.gradle
- app/src/main/java/com/example/persimmon_tree_proj/Calendar/ShareCalendarActivity.java
- app/src/main/res/layout/activity_profile_color_main.xml
- app/src/main/res/layout/activity_share_calendar.xml
기획팀이 아직 정확한 스토리보드 전달을 안해줘서 추후에 더 수정 예정
> [fix] calendar

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist_show_select_memo.java
- app/src/main/res/layout/activity_todolist_show_select_memo.xml
- app/src/main/res/layout/todolist_item.xml
메모 선택했을 때 보여지는 페이지 추가 + recycleview 선택 넘기기 기능 추가 !
> [add] select memo page

- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/Todolist_edit.java
- app/src/main/java/com/example/persimmon_tree_proj/To_do_list/list_adapter_edit.java
- app/src/main/res/drawable/todo_style_clicked.xml
- app/src/main/res/drawable/todo_style_first.xml
- app/src/main/res/layout/activity_todolist.xml
- app/src/main/res/layout/todo_edit_item.xml
- app/src/main/res/layout/todolist_item.xml
메모 선택 후 삭제 기능 추가 ~!
메모 하나도 없을 때 화면 수정
> [add] remove memo func

- app/src/main/res/layout/activity_todo_list_addlist_activity.xml
- app/src/main/res/layout/activity_todolist.xml
- app/src/main/res/layout/activity_todolist_edit.xml
style="?android:attr/borderlessButtonStyle"
> [fix] remove btn style

- app/src/main/java/com/example/persimmon_tree_proj/LodingPage_Activity.java
- app/src/main/java/com/example/persimmon_tree_proj/Main/MainActivity.java
- app/src/main/res/layout/activity_loding_page_.xml
> [fix] loading page activity

- app/src/main/java/com/example/persimmon_tree_proj/Family/ListViewAdapter.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/ListViewItem.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Make_FamilyProfile.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity.java
- app/src/main/java/com/example/persimmon_tree_proj/Family/Waitactivity2.java
- app/src/main/res/layout/activity_waitactivity.xml
- app/src/main/res/layout/activity_waitactivity2.xml
- app/src/main/res/layout/listview_item.xml
대기화면 리스트뷰 어댑터 xml 수정
가족 코드 생성시 숫자+영어만 나오도록 수정
> [add]waitactivity adapter xml / fcode(only num,string)

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/persimmon_tree_proj/QNA/QNA_Activity.java
> qlist setanswer
